spring:
  application:
    name: testcontainers-demo
  datasource:
    hikari:
      connection-timeout: 10000
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/testcontainers_demo}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default-schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
    connect-timeout: 10000
