-- Database: testcontainers_demo
CREATE DATABASE testcontainers_demo
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES
    GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT EXECUTE ON FUNCTIONS TO PUBLIC;

ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO postgres;

ALTER DEFAULT PRIVILEGES
    GRANT USAGE ON TYPES TO PUBLIC;
